import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { readFile } from "node:fs/promises";
import test, { after } from "node:test";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";
import { createServer } from "vite";

const root=fileURLToPath(new URL("..",import.meta.url));
const vite=await createServer({appType:"custom",configFile:false,root,resolve:{alias:{"@":root}},server:{middlewareMode:true,hmr:false}});after(()=>vite.close());

test("central pricing adds exactly ₹200 and rejects invalid costs",async()=>{const pricing=await vite.ssrLoadModule("/lib/commerce/pricing.ts");assert.equal(pricing.calculateSellingPrice(299),499);assert.equal(pricing.calculateSellingPrice(667),867);assert.throws(()=>pricing.calculateSellingPrice(-1),/INVALID_SOURCE_COST/)});
test("checkout accepts references only and strips manipulated totals",async()=>{const{checkoutRequestSchema}=await vite.ssrLoadModule("/lib/commerce/validation.ts");const parsed=checkoutRequestSchema.parse({checkout:{full_name:"Asha Nair",phone:"9876543210",email:"",address_line_1:"12 Lake Road",locality:"Indiranagar",city:"Bengaluru",state:"Karnataka",postal_code:"560038",country:"India"},items:[{sku:"MSH-ETH-001-M",quantity:1,unitPrice:1}],paymentMethod:"cod",idempotencyKey:"6f05818d-0e08-47b5-b6de-fb1d71e0a725",subtotal:1,total:1});assert.deepEqual(parsed.items,[{sku:"MSH-ETH-001-M",quantity:1}]);assert.equal("total" in parsed,false)});
test("checkout rejects zero, negative, excessive quantities and invalid variants",async()=>{const{cartSchema}=await vite.ssrLoadModule("/lib/commerce/validation.ts");for(const quantity of[0,-1,11])assert.equal(cartSchema.safeParse([{sku:"MSH-ETH-001-M",quantity}]).success,false);assert.equal(cartSchema.safeParse([{sku:"bad size",quantity:1}]).success,false)});
test("public catalogue projection excludes source cost and preserves unavailable variants",async()=>{const sql=await readFile(new URL("../supabase/migrations/20260830150000_commerce_hardening.sql",import.meta.url),"utf8");const view=sql.match(/create or replace view public\.public_catalogue[\s\S]*?from public\.products[\s\S]*?;/i)?.[0]||"";assert.doesNotMatch(view,/source_cost/i);assert.match(view,/available_quantity/);assert.match(view,/status='active'/)});
test("order creation and import RPCs are service-role-only and atomic",async()=>{const foundation=await readFile(new URL("../supabase/migrations/20260830103958_commerce_foundation.sql",import.meta.url),"utf8");const hardening=await readFile(new URL("../supabase/migrations/20260830150000_commerce_hardening.sql",import.meta.url),"utf8");assert.match(foundation,/for update of inv/i);assert.match(foundation,/idempotency_key uuid not null unique/i);assert.match(hardening,/pg_advisory_xact_lock/i);assert.match(hardening,/revoke all on function public\.import_catalogue[\s\S]*from public,anon,authenticated/i);assert.match(hardening,/reserved_quantity=greatest\(0,reserved_quantity-line\.quantity\)/i)});
test("catalogue importer reports a deterministic dry run",async()=>{const{stdout}=await promisify(execFile)(process.execPath,["scripts/validate-catalogue-import.mjs","catalogue/import-template.json"],{cwd:root});const report=JSON.parse(stdout);assert.equal(report.mode,"dry-run");assert.equal(report.validProducts,1);assert.equal(report.invalidProducts,0);assert.equal(report.records.products,1);assert.equal(report.records.variants,3)});
test("schema enforces non-negative inventory and free delivery",async()=>{const sql=await readFile(new URL("../supabase/migrations/20260830103958_commerce_foundation.sql",import.meta.url),"utf8");assert.match(sql,/stock_on_hand integer not null default 0 check\(stock_on_hand >= 0\)/);assert.match(sql,/reserved_quantity <= stock_on_hand/);assert.match(sql,/shipping_amount integer not null default 0 check\(shipping_amount=0\)/);assert.match(sql,/payment_status='paid'/)});
