import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { access, readFile } from "node:fs/promises";
import test, { after } from "node:test";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";
import { createServer } from "vite";

const root=fileURLToPath(new URL("..",import.meta.url));
const vite=await createServer({appType:"custom",configFile:false,root,resolve:{alias:{"@":root}},server:{middlewareMode:true,hmr:false}});after(()=>vite.close());

test("central pricing adds exactly ₹200 and rejects invalid costs",async()=>{const pricing=await vite.ssrLoadModule("/lib/commerce/pricing.ts");assert.equal(pricing.calculateSellingPrice(299),499);assert.equal(pricing.calculateSellingPrice(667),867);assert.throws(()=>pricing.calculateSellingPrice(-1),/INVALID_SOURCE_COST/)});
test("checkout accepts references only and strips manipulated totals",async()=>{const{checkoutRequestSchema}=await vite.ssrLoadModule("/lib/commerce/validation.ts");const parsed=checkoutRequestSchema.parse({checkout:{full_name:"Asha Nair",phone:"9876543210",email:"",address_line_1:"12 Lake Road",locality:"Indiranagar",city:"Bengaluru",state:"Karnataka",postal_code:"560038",country:"India"},items:[{sku:"MSH-ETH-001-M",quantity:1,unitPrice:1}],paymentMethod:"cod",idempotencyKey:"6f05818d-0e08-47b5-b6de-fb1d71e0a725",subtotal:1,total:1});assert.deepEqual(parsed.items,[{sku:"MSH-ETH-001-M",quantity:1}]);assert.equal("total" in parsed,false)});
test("checkout rejects zero, negative, excessive quantities and invalid variants",async()=>{const{cartSchema}=await vite.ssrLoadModule("/lib/commerce/validation.ts");for(const quantity of[0,-1,11])assert.equal(cartSchema.safeParse([{sku:"MSH-ETH-001-M",quantity}]).success,false);assert.equal(cartSchema.safeParse([{sku:"bad size",quantity:1}]).success,false)});
test("public catalogue projection excludes source cost and preserves unavailable variants",async()=>{const sql=await readFile(new URL("../supabase/migrations/20260830150000_commerce_hardening.sql",import.meta.url),"utf8");const view=sql.match(/create(?: or replace)? view public\.public_catalogue[\s\S]*?from public\.products[\s\S]*?;/i)?.[0]||"";assert.doesNotMatch(view,/source_cost/i);assert.match(view,/available_quantity/);assert.match(view,/status='active'/)});
test("order creation and import RPCs are service-role-only and atomic",async()=>{const foundation=await readFile(new URL("../supabase/migrations/20260830103958_commerce_foundation.sql",import.meta.url),"utf8");const hardening=await readFile(new URL("../supabase/migrations/20260830150000_commerce_hardening.sql",import.meta.url),"utf8");assert.match(foundation,/for update of inv/i);assert.match(foundation,/idempotency_key uuid not null unique/i);assert.match(hardening,/pg_advisory_xact_lock/i);assert.match(hardening,/revoke all on function public\.import_catalogue[\s\S]*from public,anon,authenticated/i);assert.match(hardening,/reserved_quantity=greatest\(0,reserved_quantity-line\.quantity\)/i)});
test("catalogue importer reports a deterministic dry run",async()=>{const{stdout}=await promisify(execFile)(process.execPath,["scripts/validate-catalogue-import.mjs","catalogue/import-template.json"],{cwd:root});const report=JSON.parse(stdout);assert.equal(report.mode,"dry-run");assert.equal(report.validProducts,1);assert.equal(report.invalidProducts,0);assert.equal(report.records.products,1);assert.equal(report.records.variants,3)});
test("schema enforces non-negative inventory and free delivery",async()=>{const sql=await readFile(new URL("../supabase/migrations/20260830103958_commerce_foundation.sql",import.meta.url),"utf8");assert.match(sql,/stock_on_hand integer not null default 0 check\(stock_on_hand >= 0\)/);assert.match(sql,/reserved_quantity <= stock_on_hand/);assert.match(sql,/shipping_amount integer not null default 0 check\(shipping_amount=0\)/);assert.match(sql,/payment_status='paid'/)});
test("sellable catalogue excludes unverified Product 15 and includes approved Products 16–26",async()=>{const{products,productPriceForSize}=await vite.ssrLoadModule("/lib/products.ts");assert.equal(products.length,25);assert.equal(new Set(products.map(product=>product.id)).size,25);assert.equal(products.some(product=>product.id==="MSH-EXP-015"),false);const expected=new Map([["MSH-EXP-011",685],["MSH-EXP-012",788],["MSH-EXP-013",726],["MSH-EXP-014",879],["MSH-EXP-016",680],["MSH-EXP-017",568],["MSH-EXP-018",551],["MSH-EXP-019",650],["MSH-EXP-020",682],["MSH-EXP-021",549],["MSH-EXP-022",641],["MSH-EXP-023",544],["MSH-EXP-024",669],["MSH-EXP-025",603],["MSH-EXP-026",616]]);for(const[sku,price]of expected){const product=products.find(candidate=>candidate.id===sku);assert.ok(product,sku);assert.equal(product.sellingPrice,price);assert.equal(product.images.length,6);assert.match(product.images[0],/01-catalogue-hero\.png$/);assert.doesNotMatch(product.images.join(" "),/(board|contact|collage|composite|six.views|showcase)/i);for(const image of product.images)await access(fileURLToPath(new URL(`../public${image}`,import.meta.url)))}const product16=products.find(product=>product.id==="MSH-EXP-016");assert.equal(productPriceForSize(product16,"XS"),680);assert.equal(productPriceForSize(product16,"S"),690);const product17=products.find(product=>product.id==="MSH-EXP-017");assert.equal(productPriceForSize(product17,"M"),568);assert.equal(productPriceForSize(product17,"S"),588);const product18=products.find(product=>product.id==="MSH-EXP-018");assert.equal(productPriceForSize(product18,"S"),551);assert.deepEqual(product18.sizes,["S","M","L","XL","XXL"]);assert.equal(productPriceForSize(products.find(product=>product.id==="MSH-EXP-019"),"S"),650);assert.equal(productPriceForSize(products.find(product=>product.id==="MSH-EXP-020"),"S"),682);const product21=products.find(product=>product.id==="MSH-EXP-021");assert.equal(productPriceForSize(product21,"S"),549);assert.equal(productPriceForSize(product21,"XXXL"),579);const product22=products.find(product=>product.id==="MSH-EXP-022");assert.deepEqual(product22.sizes,["S","M","L","XL","XXL"]);assert.equal(productPriceForSize(product22,"M"),641);const product24=products.find(product=>product.id==="MSH-EXP-024");assert.deepEqual(product24.sizes,["S","M","L","XL","XXL"]);assert.equal(productPriceForSize(product24,"XL"),679);assert.equal(productPriceForSize(products.find(product=>product.id==="MSH-EXP-025"),"XS"),603);const product26=products.find(product=>product.id==="MSH-EXP-026");assert.deepEqual(product26.sizes,["S","M"]);assert.equal(productPriceForSize(product26,"M"),616)});
test("verified replacement migration stages exact prices without inventing stock",async()=>{const sql=await readFile(new URL("../supabase/migrations/20260830200000_stage_verified_replacement_catalogue.sql",import.meta.url),"utf8");for(const sku of["MSH-EXP-016","MSH-EXP-017","MSH-EXP-018","MSH-EXP-019","MSH-EXP-020"])assert.match(sql,new RegExp(sku));assert.match(sql,/status='draft'/);assert.match(sql,/select v\.id,0,3/);assert.match(sql,/v\.source_cost\+200/);assert.doesNotMatch(sql,/stock_on_hand[^\n]*[1-9][0-9]*/i);assert.match(sql,/where external_id='MSH-EXP-015'/);assert.match(sql,/status='draft',[\s\S]*source_cost=0/)});
