import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Banknote, PackageCheck, ShieldCheck } from "lucide-react";
import { HeroCarousel } from "@/components/store/hero-carousel";
import { ProductCard } from "@/components/store/product-card";
import { getCatalogue } from "@/lib/commerce/catalogue.server";

export default async function Home() {
  const products=await getCatalogue();
  const featured=products.filter(product=>product.featured||product.bestSeller).slice(0,4);
  const expanded=products.filter(product=>product.id.startsWith("MSH-EXP-"));
  return <main><HeroCarousel/><section className="category-strip page-width"><div><h2>Shop the way you dress</h2><p>Four focused edits, no endless marketplace scroll.</p></div><div className="category-links">{[["Dresses","/images/MSH-WES-008/02-front-model.png"],["Kurtis","/images/MSH-ETH-001/02-front-model.png"],["Kurta Sets","/images/MSH-SET-003/02-front-model.png"],["Gowns","/images/MSH-GWN-006/02-front-model.png"]].map(([label,image])=><Link href={`/shop?category=${encodeURIComponent(label)}`} key={label}><span><Image src={image} alt="" fill sizes="120px"/></span>{label}</Link>)}</div></section>{expanded.length>0&&<section className="product-section page-width"><div className="section-heading"><div><h2>Newly added styles</h2><p>Fresh additions for workdays, everyday plans and festive invitations.</p></div><Link href="/shop?sort=newest" className="button text-button">Shop new arrivals <ArrowRight/></Link></div><div className="product-grid">{expanded.map(product=><ProductCard key={product.id} product={product}/>)}</div></section>}<section className="product-section page-width"><div className="section-heading"><div><h2>Most-loved styles</h2><p>Easy silhouettes chosen for everyday plans and special invitations.</p></div><Link href="/shop?sort=best" className="button text-button">Shop all <ArrowRight/></Link></div><div className="product-grid">{featured.map(product=><ProductCard key={product.id} product={product}/>)}</div></section><section className="occasion-banner page-width"><div className="occasion-image"><Image src="/images/MSH-SET-004/03-occasion-lifestyle.png" alt="Purple three-piece festive set" fill sizes="(max-width:768px) 100vw,50vw"/></div><div><h2>An invitation deserves an easy yes.</h2><p>Festive sets and flowing gowns that feel special without the luxury markup.</p><Link href="/shop?occasion=Festive+wear" className="button light">Shop occasion wear</Link></div></section><section className="benefits page-width"><div><ShieldCheck/><h2>Thoughtful shopping</h2><p>Clear product details and no surprise delivery charge.</p></div><div><Banknote/><h2>Pay when it arrives</h2><p>Cash on Delivery keeps checkout simple and familiar.</p></div><div><PackageCheck/><h2>Delivery included</h2><p>Your displayed total is the final product total. Standard delivery is free.</p></div></section></main>;
}
