export type Product = { id:string; slug:string; name:string; category:"Kurtis"|"Kurta Sets"|"Dresses"|"Gowns"; collection:string; occasion:string; sellingPrice:number; images:string[]; sizes:string[]; colour:string; material:string; description:string; featured?:boolean; newArrival?:boolean; bestSeller?:boolean };
const names=["catalogue-hero","front-model","occasion-lifestyle","three-quarter-view","fabric-detail","product-info-card"];
const imageSet=(sku:string)=>names.map((name,index)=>`/images/${sku}/0${index+1}-${name}.png`);
export const products:Product[]=[
{id:"MSH-ETH-001",slug:"ajrakh-black-cotton-straight-kurti",name:"Ajrakh Black Cotton Straight Kurti",category:"Kurtis",collection:"Everyday Ethnic",occasion:"Daily wear",sellingPrice:694,images:imageSet("MSH-ETH-001"),sizes:["XS","S","M","L","XL","XXL","3XL","4XL","5XL","6XL"],material:"Cotton Cambric",colour:"Black",description:"Ajrakh-inspired motifs with a comfortable straight silhouette for workdays and everyday outings.",featured:true,bestSeller:true},
{id:"MSH-ETH-002",slug:"teal-art-silk-embroidered-a-line-kurta",name:"Teal Art-Silk Embroidered A-Line Kurta",category:"Kurtis",collection:"Festive Ethnic",occasion:"Festive wear",sellingPrice:609,images:imageSet("MSH-ETH-002"),sizes:["XXS","XS","S","M","L","XL","XXL","3XL","4XL"],material:"Art Silk",colour:"Teal",description:"A jewel-toned A-line kurta with embroidered neckline detailing for festive moments.",newArrival:true},
{id:"MSH-SET-003",slug:"peach-printed-kurta-palazzo-set",name:"Peach Printed Kurta Palazzo Set",category:"Kurta Sets",collection:"Everyday Sets",occasion:"Casual outing",sellingPrice:675,images:imageSet("MSH-SET-003"),sizes:["XXS","XS","S","M","L","XL","XXL","3XL","4XL","5XL"],material:"Rayon",colour:"Peach",description:"An easy rayon kurta-and-palazzo pairing with a soft peach print.",newArrival:true},
{id:"MSH-SET-004",slug:"purple-aliya-cut-three-piece-set",name:"Purple Aliya-Cut Three-Piece Set",category:"Kurta Sets",collection:"Festive Sets",occasion:"Wedding guest",sellingPrice:816,images:imageSet("MSH-SET-004"),sizes:["XS","S","M","L","XL","XXL","3XL","4XL","5XL"],material:"Rayon",colour:"Purple",description:"A flowing three-piece ensemble with coordinated pants and dupatta.",featured:true},
{id:"MSH-GWN-005",slug:"purple-sequin-embroidered-anarkali",name:"Purple Sequin-Embroidered Anarkali",category:"Gowns",collection:"Wedding & Festive",occasion:"Evening party",sellingPrice:832,images:imageSet("MSH-GWN-005"),sizes:["S","M","L","XL","XXL","3XL","4XL","5XL"],material:"Cotton Blend",colour:"Purple",description:"A generous ankle-length Anarkali with delicate sequin accents.",bestSeller:true},
{id:"MSH-GWN-006",slug:"ivory-floral-rayon-flared-gown",name:"Ivory Floral Rayon Flared Gown",category:"Gowns",collection:"Day Occasion",occasion:"Brunch",sellingPrice:690,images:imageSet("MSH-GWN-006"),sizes:["S","M","L","XL","XXL","3XL","4XL","5XL"],material:"Rayon",colour:"Ivory",description:"A light floral gown with a sweeping ankle-length flare.",newArrival:true},
{id:"MSH-WES-007",slug:"pink-tiered-georgette-maxi-dress",name:"Pink Tiered Georgette Maxi Dress",category:"Dresses",collection:"Party & Brunch",occasion:"Brunch date",sellingPrice:867,images:imageSet("MSH-WES-007"),sizes:["XS","S","M","L","XL","XXL"],material:"Georgette",colour:"Pink",description:"A vibrant floral maxi with puff sleeves and a tiered skirt.",featured:true,bestSeller:true},
{id:"MSH-WES-008",slug:"black-floral-fit-and-flare-maxi-dress",name:"Black Floral Fit-and-Flare Maxi Dress",category:"Dresses",collection:"Casual Western",occasion:"Evening",sellingPrice:679,images:imageSet("MSH-WES-008"),sizes:["S","M","L","XL","XXL"],material:"Cotton Blend",colour:"Black",description:"A fitted bodice and flowing floral skirt for casual plans and parties.",bestSeller:true},
{id:"MSH-WES-009",slug:"white-floral-puff-sleeve-mini-dress",name:"White Floral Puff-Sleeve Mini Dress",category:"Dresses",collection:"College & Casual",occasion:"Casual party",sellingPrice:758,images:imageSet("MSH-WES-009"),sizes:["S","M","L","XL"],material:"Rayon",colour:"White",description:"A playful floral mini with puff sleeves and a softly flared shape.",newArrival:true},
{id:"MSH-WES-010",slug:"lemon-yellow-bodycon-midi-dress",name:"Lemon Yellow Bodycon Midi Dress",category:"Dresses",collection:"Evening Party",occasion:"Date night",sellingPrice:837,images:imageSet("MSH-WES-010"),sizes:["XS","S","M","L","XL"],material:"Lycra",colour:"Lemon Yellow",description:"A clean bodycon midi with a square neckline and front slit."}];
export const formatPrice=(price:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(price);
export const findProduct=(slug:string)=>products.find(product=>product.slug===slug);
