import Image from "next/image";
import Link from "next/link";
import { Check } from "lucide-react";
import { formatPrice } from "@/lib/products";
import type { OrderReceipt } from "@/lib/commerce/types";

export function OrderSuccess({order,receipt}:{order:string;receipt:OrderReceipt|null}) {
  if(!receipt)return <main className="page-shell success-page"><h1>We can’t show this order</h1><p>The private confirmation link is missing or has expired. Your order may still have been placed.</p><Link href="/shop" className="button primary">Return to shop</Link></main>;
  const address=receipt.shipping_address;
  return <main className="page-shell success-page"><div className="success-mark"><Check aria-hidden="true"/></div><h1>Order confirmed</h1><p>Thanks, {receipt.customer_name}. We’ve received your {receipt.payment_method==="cod"?"Cash on Delivery":"online payment"} order.</p><dl><div><dt>Order number</dt><dd>{order}</dd></div><div><dt>Payment</dt><dd>{receipt.payment_method==="cod"?`Cash on Delivery · ${receipt.payment_status}`:`Online payment · ${receipt.payment_status}`}</dd></div><div><dt>Order status</dt><dd>{receipt.order_status}</dd></div><div><dt>Delivery address</dt><dd>{address.address_line_1}{address.address_line_2?`, ${address.address_line_2}`:""}, {address.locality}, {address.city}, {address.state} {address.postal_code}</dd></div></dl><section className="confirmation-items" aria-labelledby="confirmation-items-title"><h2 id="confirmation-items-title">Order items</h2>{receipt.order_items.map(item=><article key={item.sku}>{item.image_url&&<span className="confirmation-thumb"><Image src={item.image_url} alt="" fill sizes="64px"/></span>}<span><strong>{item.product_name}</strong><small>Size {item.size}{item.colour?` · ${item.colour}`:""} · Qty {item.quantity}</small></span><strong>{formatPrice(item.line_total)}</strong></article>)}</section><dl className="confirmation-totals"><div><dt>Subtotal</dt><dd>{formatPrice(receipt.subtotal)}</dd></div><div><dt>Delivery</dt><dd>FREE</dd></div>{receipt.discount_amount>0&&<div><dt>Discount</dt><dd>−{formatPrice(receipt.discount_amount)}</dd></div>}<div><dt>Total</dt><dd>{formatPrice(receipt.total_amount)}</dd></div></dl><p className="success-note">Keep your order number handy. Tracking will be shared only after dispatch.</p><Link href="/shop" className="button primary">Continue shopping</Link></main>;
}
