-- Five approved catalogue additions. Inventory starts at zero until operations verifies physical stock.
select public.import_catalogue(
  $$[
    {"externalId":"MSH-EXP-011","name":"Sky Blue Cotton Kurta & Pant Set","slug":"sky-blue-cotton-kurta-pant-set","category":"kurta-sets","sourceCost":485,"description":"A breathable sky-blue cotton kurta and pant pairing for everyday office, college and casual wear.","material":"Cotton","colour":"Sky Blue","occasion":"Office edit","sizes":["M","L","XL","XXL","3XL"],"stock":0,"newArrival":true,"images":[{"url":"/images/MSH-EXP-011/01-catalogue-board.png","alt":"Sky Blue Cotton Kurta and Pant Set catalogue board"}]},
    {"externalId":"MSH-EXP-012","name":"Maroon Printed Flared Gown with Dupatta","slug":"maroon-printed-flared-gown-dupatta","category":"gowns","sourceCost":588,"description":"A graceful printed flared gown with a coordinated dupatta for festive gatherings and special occasions.","material":"Poly Georgette","colour":"Maroon","occasion":"Festive look","sizes":["S","M","L","XL"],"stock":0,"newArrival":true,"images":[{"url":"/images/MSH-EXP-012/01-catalogue-board.png","alt":"Maroon Printed Flared Gown with Dupatta catalogue board"}]},
    {"externalId":"MSH-EXP-013","name":"Checked A-Line Maxi Dress","slug":"checked-a-line-maxi-dress","category":"dresses","sourceCost":526,"description":"A relaxed checked A-line maxi with a collared waist detail for easy everyday styling.","material":"Printed Fabric","colour":"Green/Navy Check","occasion":"Everyday style","sizes":["S","M","L","XL","XXL"],"stock":0,"newArrival":true,"images":[{"url":"/images/MSH-EXP-013/01-catalogue-board.png","alt":"Checked A-Line Maxi Dress catalogue board"}]},
    {"externalId":"MSH-EXP-014","name":"Black Anarkali Gown with Dupatta","slug":"black-anarkali-gown-dupatta","category":"gowns","sourceCost":679,"description":"An elegant black Anarkali gown with a matching dupatta and subtle festive detailing.","material":"Faux Georgette","colour":"Black","occasion":"Evening edit","sizes":["S","M","L","XL"],"stock":0,"newArrival":true,"images":[{"url":"/images/MSH-EXP-014/01-catalogue-board.png","alt":"Black Anarkali Gown with Dupatta catalogue board"}]},
    {"externalId":"MSH-EXP-015","name":"Maroon Floral Anarkali Gown Set","slug":"maroon-floral-anarkali-gown-set","category":"gowns","sourceCost":588,"description":"A flowing maroon floral Anarkali-style gown with coordinated dupatta for festive occasions.","material":"Printed Fabric","colour":"Maroon","occasion":"Occasion wear","sizes":["S","M","L","XL"],"stock":0,"newArrival":true,"images":[{"url":"/images/MSH-EXP-015/01-catalogue-board.png","alt":"Maroon Floral Anarkali Gown Set catalogue board"}]}
  ]$$::jsonb,
  false
);
